name: Deploy Fast API Todos Apps
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  push-store-image:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "."
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@main
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: mutantNeko
          password: ${{ secrets.GH_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ghcr.io/mutantNeko/fastapi-app:latest
          cache-from: type=registry,ref=ghcr.io/mutantneko/fastapi-app:cache
          cache-to: type=registry,mode=max,ref=ghcr.io/mutantneko/fastapi-app:cache,image-manifest=true
      # - name: executing remote ssh commands using password
      #   uses: appleboy/ssh-action@v1.0.3
      #   with:
      #     host: ${{ secrets.SSH_HOST }}
      #     username: ubuntu
      #     key: ${{ secrets.SSH_KEY }}
      #     script: |
      #       docker login ghcr.io -u mutantNeko -p ${{ secrets.GHCR_TOKEN }}
      #       docker compose pull fastapi-app
      #       docker compose up --force-recreate --build -d fastapi-app
      #       docker system prune -a -f
